<?php

namespace Database\Factories;

use App\Models\Supplier;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Supplier>
 */
class SupplierFactory extends Factory
{
    protected $model = Supplier::class;

    public function definition(): array
    {
        return [
            // supplier_code / invoice_prefix are auto-generated by
            // Supplier::booted() when blank.
            'name'   => fake()->unique()->company(),
            'phone'  => fake()->numerify('##########'),
            'status' => true,
        ];
    }
}
