<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Missing Stock — {{ $audit->audit_number }}</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; font-size: 10px; color: #1f2430; }
        h1 { font-size: 16px; margin: 0 0 4px; }
        .muted { color: #6b7280; }
        .header-table { width: 100%; margin-bottom: 14px; border-bottom: 2px solid #1f2430; padding-bottom: 8px; }
        .header-table td { vertical-align: top; padding: 0; }
        .text-right { text-align: right; }
        table.report { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.report th { background: #f4f5f7; text-align: left; padding: 5px 6px; font-size: 9px; text-transform: uppercase; border-bottom: 1px solid #d1d5db; }
        table.report td { padding: 5px 6px; border-bottom: 1px solid #eceef1; font-size: 9.5px; }
        table.report tr:nth-child(even) { background: #fafafa; }
        .badge { display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 8px; background: #f4f5f7; color: #6b7280; }
        .summary { margin-top: 10px; font-size: 10px; }
        .empty-row { text-align: center; color: #9ca3af; padding: 20px 0; }
        .footer { margin-top: 14px; font-size: 8px; color: #9ca3af; }
    </style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td>
                <h1>Missing Stock Report</h1>
                <div class="muted">Audit {{ $audit->audit_number }} &middot; {{ $audit->location?->name }}</div>
            </td>
            <td class="text-right">
                <div><strong>Audit Date:</strong> {{ optional($audit->audit_date)->format('d M Y') }}</div>
                <div><strong>Stone:</strong> {{ $audit->categoryLabel() }}</div>
                <div><strong>Status:</strong> {{ $audit->statusLabel() }}</div>
                <div><strong>Generated:</strong> {{ $generatedAt->format('d M Y H:i') }}</div>
            </td>
        </tr>
    </table>

    <div class="summary">
        Expected: <strong>{{ (int) $audit->expected_total }}</strong> &middot;
        Matched: <strong>{{ (int) $audit->matched_total }}</strong> &middot;
        Missing: <strong>{{ $audit->missingTotal() }}</strong>
    </div>

    <table class="report">
        <thead>
            <tr>
                <th>#</th>
                <th>Lot Code</th>
                <th>Product</th>
                <th>SKU</th>
                <th>Stone</th>
                <th>Supplier</th>
                <th>Invoice #</th>
                <th>Purchase Date</th>
                <th class="text-right">Cost Price</th>
                <th class="text-right">Qty</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($items as $index => $item)
                @php
                    $purchase = $item->purchaseProduct?->line?->purchase;
                    $supplier = $purchase?->supplier;
                @endphp
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>
                        {{ $item->lot_code ?: '—' }}
                        @if ($item->isUntrackable())
                            <span class="badge">no lot code</span>
                        @endif
                    </td>
                    <td>{{ $item->product?->title ?? '—' }}</td>
                    <td>{{ $item->product?->sku ?? '—' }}</td>
                    <td>{{ $item->product?->category?->name ?? '—' }}</td>
                    <td>{{ $supplier?->company_name ?: ($supplier?->name ?? '—') }}</td>
                    <td>{{ $purchase?->invoice_number ?? '—' }}</td>
                    <td>{{ $purchase?->purchase_date?->format('d M Y') ?? '—' }}</td>
                    <td class="text-right">{{ $settings->formatMoney((float) ($item->purchaseProduct?->price ?? 0)) }}</td>
                    <td class="text-right">1</td>
                </tr>
            @empty
                <tr>
                    <td colspan="10" class="empty-row">No missing stock — everything expected was scanned.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by Paces &middot; {{ $generatedAt->format('d M Y H:i') }}</div>
</body>
</html>
